name: "Get listed NFTs"
on:
  schedule:
  - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  request:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          ref: remote
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install -r requirements.txt
      
      - name: Getting Listed NFTs
        env:
            API_KEY: ${{ secrets.API_KEY }}
            COLLECTION: ${{ secrets.COLLECTION }}
        run: |
          python3 listedNfts.py
          echo "## Getting listed NFTs" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      
      - name: Checking
        env:
            API_KEY: ${{ secrets.API_KEY }}
            COLLECTION: ${{ secrets.COLLECTION }}
            PRIVATE_URL: ${{ secrets.PRIVATE_URL }}
            PASSWORD: ${{ secrets.PASSWORD }}
            FROM: ${{ secrets.FROM }}
            TO: ${{ secrets.TO }}
        run: |
          python3 check.py
          echo "## Getting unclaimed NFTs listed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      
      - name: Get current date
        id: date
        run: |
          export TZ=America/Argentina/Buenos_Aires
          echo "JOB_DATE=$(date +'%Y-%m-%d %H:%Mhs')" >> $GITHUB_ENV
          echo "## Getting job date and hour" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      
      - name : "Ensure trusted environment"
        run :  git config --global --add safe.directory /__w/Listed_NFT/Listed_NFT
      
      - name: "Add change name summary"
        run: |
          echo "## Commiting results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      
      - name: "Update commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "request: ${{ env.JOB_DATE }}"
          #commit_options: "--amend"
          push_options: "--force"
          skip_fetch: true
